name:                store-compare
version:             0.1.0.0
github:              "turanct/store-compare"
license:             BSD3
author:              "Toon Daelman"
maintainer:          "spinnewebber_toon@hotmail.com"
copyright:           "2018 Toon Daelman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/turanct/store-compare#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - http-client
  - http-client-tls
  - http-conduit
  - bytestring
  - text
  - xml-conduit
  - html-conduit

executables:
  store-compare-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - store-compare
    - servant-server
    - aeson
    - wai
    - warp

tests:
  store-compare-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - store-compare
